server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://jvepsmxdpcptud:cf552671d7f928134dfb304e49acba50c2e93fe32220323b688b354c4b7a37c7@ec2-34-230-167-186.compute-1.amazonaws.com:5432/d4tpd02sq6a0fj
    username: jvepsmxdpcptud
    password: cf552671d7f928134dfb304e49acba50c2e93fe32220323b688b354c4b7a37c7
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: none

application:
  description: Projeto criado para o bootcamp Digital Innovation One - Santander / Backend
